name: Security Audit

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  audit:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NodeJS Installation
        uses: actions/setup-node@v1
      - name: NPM Audit
        run: npm audit --production
